const SUCCESS_LOG_IN = 'SUCCESS_LOG_IN'
const ERROR_LOG_IN = 'ERROR_LOG_IN'
const SET_LOADING_LOG_IN_STATE = 'SET_LOADING_LOG_IN_STATE'
const LOG_OUT = 'LOG_OUT'
const CHANGE_PATH = 'CHANGE_PATH'

const ActionTypes = {
    SUCCESS_LOG_IN,
    ERROR_LOG_IN,
    SET_LOADING_LOG_IN_STATE,
    LOG_OUT,
    CHANGE_PATH
}

export default ActionTypes