const SUCCESS_LOG_IN = 'SUCCESS_LOG_IN'
const ERROR_LOG_IN = 'ERROR_LOG_IN'
const SET_LOADING_LOG_IN_STATE = 'SET_LOADING_LOG_IN_STATE'
const LOG_OUT = 'LOG_OUT'
const CHANGE_PATH = 'CHANGE_PATH'

// VENDORS
const FETCH_VENDORS = 'FETCH_VENDORS'
const SET_VENDORS = 'SET_VENDORS'
const DELETE_VENDOR = 'DELETE_VENDOR'
const SET_UPLOADING_NEW_VENDOR = 'SET_UPLOADING_NEW_VENDOR'
const SET_FETCH_VENDORS_LOADING = 'SET_FETCH_VENDORS_LOADING'
const ERROR_ADDING_A_VENDOR = 'ERROR_ADDING_A_VENDOR'

const ActionTypes = {
    SUCCESS_LOG_IN,
    ERROR_LOG_IN,
    SET_LOADING_LOG_IN_STATE,
    LOG_OUT,
    CHANGE_PATH,
    FETCH_VENDORS,
    SET_VENDORS,
    DELETE_VENDOR,
    SET_UPLOADING_NEW_VENDOR,
    SET_FETCH_VENDORS_LOADING,
    ERROR_ADDING_A_VENDOR
}

export default ActionTypes